apiVersion: v1
kind: Service
metadata:
  labels:
    app: blackbox-exporter
  name: k8g-pgmon-blackbox-exporter
  namespace: pgmon
spec:
  ports:
  - name: blackbox
    port: 9115
    protocol: TCP
  selector:
    app: blackbox-exporter
  type: ClusterIP
