apiVersion: v1
kind: Service
metadata:
  name: k8s-pgmon-alertmanager
  namespace: pgmon
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Alertmanager"
spec:
  type: NodePort
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
    nodePort: 30004
  selector:
    k8s-app: alertmanager
