apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-external
  namespace: pgmon
  labels:
    k8s-app: etcd-external-cluster
subsets:
- addresses:
  - ip: 172.25.50.16
  - ip: 172.25.50.17
  - ip: 172.25.50.18
  ports:
  - name: metrics
    port: 2379
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-external
  namespace: pgmon
  labels:
    k8s-app: etcd-external-cluster
spec:
  selector:
    component: etcd-external
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 2379
    protocol: TCP
    targetPort: 2379
